points:
  Berlin:
    lat: 52.516391
    lon: 13.378679
  Hamburg:
    lat: 53.549531
    lon: 9.9624856

meteostat:
  url : "https://meteostat.p.rapidapi.com/point/hourly"
  sub_key : "data"
  start_date_param: "start"
  end_date_param: "end"

brightsky:
  url: "https://api.brightsky.dev/weather"
  sub_key : "weather"
  start_date_param: "date"
  end_date_param: "last_date"