CREATE TABLE weather_forecast (
    weather_time        TIMESTAMPTZ,
    city                TEXT,
    forecast_type       TEXT,
    provider            TEXT,
    temperature         NUMERIC,
    apparenttemperature NUMERIC,
    dewpoint            NUMERIC,
    humidity            NUMERIC,
    precipintensity     NUMERIC,
    precipprobability   NUMERIC,
    preciptype          TEXT,
    windbearing         NUMERIC,
    windspeed           NUMERIC,
    windgust            NUMERIC,
    pressure            NUMERIC,
    visibility          NUMERIC,
    cloudcover          NUMERIC,
    uvindex             NUMERIC,
    summary             TEXT,
    icon                TEXT,
    create_time         TIMESTAMPTZ,
    PRIMARY KEY (weather_time, city, forecast_type, provider)
)