CREATE TABLE weather_forecast (
    id                  SERIAL PRIMARY KEY,
    create_time         TIMESTAMPTZ,
    weather_time        TIMESTAMPTZ,
    temperature         NUMERIC,
    apparenttemperature NUMERIC,
    dewpoint            NUMERIC,
    humidity            NUMERIC,
    precipintensity     NUMERIC,
    precipprobability   NUMERIC,
    preciptype          TEXT,
    windbearing         NUMERIC,
    windspeed           NUMERIC,
    windgust            NUMERIC,
    pressure            NUMERIC,
    visibility          NUMERIC,
    cloudcover          NUMERIC,
    uvindex             NUMERIC,
    summary             TEXT,
    icon                TEXT,
    city                TEXT,
    provider            TEXT,
    forecast_type       TEXT
)